In [ ]:
# Task 21: Missing Value Analysis

## Objective
Identify missing values in a dataset, calculate column-wise
missing-value counts and percentages, and identify columns
that require missing-data treatment.

## Deliverables
- Missing-value summary
- Column-wise missing-value counts
- Missing-value percentages
- Identification of columns requiring treatment
- Explanation of missing-data observations

In [1]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
data = {
    "student_id": [
        1001, 1002, 1003, 1004, 1005, 1006,
        1007, 1008, 1009, 1010, 1011, 1012
    ],

    "name": [
        "Aarav", "Diya", "Kabir", "Ananya",
        "Ishaan", "Meera", "Rohan", "Sara",
        "Vivaan", "Aditi", "Arjun", "Nisha"
    ],

    "department": [
        "Computer Science", "Electronics", "Mechanical",
        "Computer Science", "Civil", "Electronics",
        "Mechanical", "Computer Science", "Civil",
        "Electronics", "Mechanical", np.nan
    ],

    "age": [
        20, 21, np.nan, 22, 21, 20,
        22, 21, 20, 22, 21, 20
    ],

    "marks": [
        86, np.nan, 74, 95, 68, 88,
        np.nan, 93, 72, 84, 77, 90
    ],

    "attendance": [
        92, 88, 79, np.nan, 72, 90,
        85, 94, np.nan, 86, 75, 91
    ]
}

df = pd.DataFrame(data)

print("Student dataset created successfully!")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

display(df)

Student dataset created successfully!
Number of rows: 12
Number of columns: 6

    student_id    name        department   age  marks  attendance
0         1001   Aarav  Computer Science  20.0   86.0        92.0
1         1002    Diya       Electronics  21.0    NaN        88.0
2         1003   Kabir        Mechanical   NaN   74.0        79.0
3         1004  Ananya  Computer Science  22.0   95.0         NaN
4         1005  Ishaan             Civil  21.0   68.0        72.0
5         1006   Meera       Electronics  20.0   88.0        90.0
6         1007   Rohan        Mechanical  22.0    NaN        85.0
7         1008    Sara  Computer Science  21.0   93.0        94.0
8         1009  Vivaan             Civil  20.0   72.0         NaN
9         1010   Aditi       Electronics  22.0   84.0        86.0
10        1011   Arjun        Mechanical  21.0   77.0        75.0
11        1012   Nisha               NaN  20.0   90.0        91.0

In [3]:
# Save the dataset as a CSV file
df.to_csv("missing_values_dataset.csv", index=False)

# Load the CSV file using Pandas
df = pd.read_csv("missing_values_dataset.csv")

print("CSV dataset loaded successfully!")

display(df.head(12))

CSV dataset loaded successfully!

    student_id    name        department   age  marks  attendance
0         1001   Aarav  Computer Science  20.0   86.0        92.0
1         1002    Diya       Electronics  21.0    NaN        88.0
2         1003   Kabir        Mechanical   NaN   74.0        79.0
3         1004  Ananya  Computer Science  22.0   95.0         NaN
4         1005  Ishaan             Civil  21.0   68.0        72.0
5         1006   Meera       Electronics  20.0   88.0        90.0
6         1007   Rohan        Mechanical  22.0    NaN        85.0
7         1008    Sara  Computer Science  21.0   93.0        94.0
8         1009  Vivaan             Civil  20.0   72.0         NaN
9         1010   Aditi       Electronics  22.0   84.0        86.0
10        1011   Arjun        Mechanical  21.0   77.0        75.0
11        1012   Nisha               NaN  20.0   90.0        91.0

In [4]:
print("MISSING VALUE BOOLEAN CHECK")

missing_boolean = df.isnull()

display(missing_boolean)

MISSING VALUE BOOLEAN CHECK

    student_id   name  department    age  marks  attendance
0        False  False       False  False  False       False
1        False  False       False  False   True       False
2        False  False       False   True  False       False
3        False  False       False  False  False        True
4        False  False       False  False  False       False
5        False  False       False  False  False       False
6        False  False       False  False   True       False
7        False  False       False  False  False       False
8        False  False       False  False  False        True
9        False  False       False  False  False       False
10       False  False       False  False  False       False
11       False  False        True  False  False       False

In [5]:
print("MISSING VALUE CHECK USING isna()")

display(df.isna())

MISSING VALUE CHECK USING isna()

    student_id   name  department    age  marks  attendance
0        False  False       False  False  False       False
1        False  False       False  False   True       False
2        False  False       False   True  False       False
3        False  False       False  False  False        True
4        False  False       False  False  False       False
5        False  False       False  False  False       False
6        False  False       False  False   True       False
7        False  False       False  False  False       False
8        False  False       False  False  False        True
9        False  False       False  False  False       False
10       False  False       False  False  False       False
11       False  False        True  False  False       False

In [6]:
print("MISSING VALUES IN EACH COLUMN")

missing_counts = df.isnull().sum()

display(missing_counts.to_frame(
    name="Missing Value Count"
))

MISSING VALUES IN EACH COLUMN

            Missing Value Count
student_id                    0
name                          0
department                    1
age                           1
marks                         2
attendance                    2

In [7]:
print("MISSING VALUE PERCENTAGES")

missing_percentage = (
    df.isnull().sum() / len(df)
) * 100

display(
    missing_percentage.round(2).to_frame(
        name="Missing Percentage"
    )
)

MISSING VALUE PERCENTAGES

            Missing Percentage
student_id                0.00
name                      0.00
department                8.33
age                       8.33
marks                    16.67
attendance               16.67

In [8]:
missing_summary = pd.DataFrame({
    "Column": df.columns,

    "Data Type": [
        str(df[column].dtype)
        for column in df.columns
    ],

    "Total Records": len(df),

    "Missing Count": [
        df[column].isnull().sum()
        for column in df.columns
    ],

    "Missing Percentage": [
        round(df[column].isnull().mean() * 100, 2)
        for column in df.columns
    ],

    "Treatment Required": [
        df[column].isnull().any()
        for column in df.columns
    ]
})

print("COMPLETE MISSING VALUE SUMMARY")

display(missing_summary)

COMPLETE MISSING VALUE SUMMARY

,Column,Data Type,Total Records,Missing Count,Missing Percentage,Treatment Required
0,student_id,int64,12,0,0.00,False
1,name,object,12,0,0.00,False
2,department,object,12,1,8.33,True
3,age,float64,12,1,8.33,True
4,marks,float64,12,2,16.67,True
5,attendance,float64,12,2,16.67,True

In [9]:
columns_to_treat = missing_summary[
    missing_summary["Treatment Required"] == True
]

print("COLUMNS REQUIRING MISSING VALUE TREATMENT")

display(columns_to_treat)

print("\nColumn names requiring treatment:")

print(columns_to_treat["Column"].tolist())

COLUMNS REQUIRING MISSING VALUE TREATMENT

,Column,Data Type,Total Records,Missing Count,Missing Percentage,Treatment Required
2,department,object,12,1,8.33,True
3,age,float64,12,1,8.33,True
4,marks,float64,12,2,16.67,True
5,attendance,float64,12,2,16.67,True

Column names requiring treatment:
['department', 'age', 'marks', 'attendance']

In [10]:
print("ROWS CONTAINING MISSING VALUES")

missing_records = df[df.isnull().any(axis=1)]

display(missing_records)

print(
    "\nTotal rows containing missing values:",
    len(missing_records)
)

ROWS CONTAINING MISSING VALUES

    student_id    name        department   age  marks  attendance
1         1002    Diya       Electronics  21.0    NaN        88.0
2         1003   Kabir        Mechanical   NaN   74.0        79.0
3         1004  Ananya  Computer Science  22.0   95.0         NaN
6         1007   Rohan        Mechanical  22.0    NaN        85.0
8         1009  Vivaan             Civil  20.0   72.0         NaN
11        1012   Nisha               NaN  20.0   90.0        91.0

Total rows containing missing values: 6

In [11]:
total_cells = df.size

total_missing = df.isnull().sum().sum()

total_present = total_cells - total_missing

overall_missing_percentage = (
    total_missing / total_cells
) * 100

print("=" * 55)
print("        OVERALL MISSING VALUE ANALYSIS")
print("=" * 55)

print("Total rows:", df.shape[0])
print("Total columns:", df.shape[1])
print("Total cells:", total_cells)
print("Present values:", total_present)
print("Missing values:", total_missing)

print(
    "Overall missing percentage:",
    round(overall_missing_percentage, 2), "%"
)

=======================================================
        OVERALL MISSING VALUE ANALYSIS
=======================================================
Total rows: 12
Total columns: 6
Total cells: 72
Present values: 66
Missing values: 6
Overall missing percentage: 8.33 %

In [12]:
treatment_recommendations = {
    "department": "Mode or Unknown category",
    "age": "Median imputation",
    "marks": "Median imputation",
    "attendance": "Median imputation"
}

print("MISSING VALUE TREATMENT RECOMMENDATIONS")

for column, recommendation in treatment_recommendations.items():
    if df[column].isnull().any():
        print(f"{column}: {recommendation}")

MISSING VALUE TREATMENT RECOMMENDATIONS
department: Mode or Unknown category
age: Median imputation
marks: Median imputation
attendance: Median imputation

In [13]:
missing_summary.to_csv(
    "missing_value_summary.csv",
    index=False
)

print("Missing-value summary exported successfully!")

Missing-value summary exported successfully!

In [14]:
from google.colab import files

files.download("missing_values_dataset.csv")
files.download("missing_value_summary.csv")